config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  get 'logout' => 'sessions#destroy'
  get 'detailed_report' => 'projects#detailed_report'
  get 'employee_report' => 'employees#employee_report'
  post 'employee_report' => 'employees#employee_report'
  get 'project_report' => 'projects#project_report'
  post 'project_report' => 'projects#project_report'  
  get 'users/old_password_check'
  get 'users/change_password'
  post 'users/change_password_update'
  get 'projects/project_active_status'
  get 'users/new_password'
  post 'users/set_new_password'
  get 'clients/sample_csv'
  get 'sessions/new'
  post 'employees/import_employee'
  get 'clients/dashboard'
  
  resources :sessions
  resources :users  
  resources :projects
  resources :employees
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'is_absent' => 'time_sheets#is_absent'
      get 'time_sheets/date'
      get 'employees/assigned_project'
      get 'users/forgot_password'
      get 'projects/approval_status'
      get 'time_sheets/time_approval_status'
      post 'employees/image_upload'
      get 'logs/call_index'
      get 'logs/call_show'
      post 'logs/call_create'
      put 'logs/call_update'
      get 'logs/message_index'
      get 'logs/message_show'
      post 'logs/message_create'
      put 'logs/message_update'
      get 'time_sheets/project_working_hours'
      get 'clients/client_contacts'
      get 'clients/client_projects'
      get 'employees/unassigned_project'
      get 'time_sheets/cost_estimate'
      get 'contacts/client_contacts'
      get 'projects/project_employee'
      get 'time_sheets/employee_time_sheet'
      get 'employees/project_assign'
      get 'users/user_registration'
      get 'users/login_validation'
      get 'employees/employee_details'	
      resources :contacts
      resources :users	
      resources :employees
      resources :clients
      resources :projects
      resources :roles
      resources :time_sheets
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  require 'carrierwave'
  require 'csv'
  require 'activerecord-import'
  require 'rubygems'
  require 'roo'
  require 'spreadsheet'
  mount_uploader :image, AvatarUploader
  has_many :project_employees, dependent: :destroy
  has_many :time_sheets, dependent: :destroy
  has_one :user, dependent: :destroy
  validates_uniqueness_of :email
  validates_length_of :mobile_number,:in => 10..10, :on => :create
  validates :email, uniqueness: { case_sensitive: false}, length: { in: 6..100 }
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  def self.import_data(params)

    extn=File.extname(params["employee"]["address"].tempfile)
    extn=extn.downcase
    if extn == ".xlsx"
       file = Roo::Spreadsheet.open(params["employee"]["address"].tempfile)
       file = file.sheet(file.sheets.first)
       rows = file.map { |e| e }
    elsif extn == ".xls"
       file=Spreadsheet.open(params["employee"]["address"].tempfile)
       rows=file.worksheet(0).map{|kk| kk}
    elsif extn == ".csv"   
       rows=File.open(params["employee"]["address"].tempfile,"r").collect{|i| i.chomp.split(",")}     
    else
       return "Invalid File"   
    end   
    headers = rows.shift.count  
    if headers == 13
      array = []
      rows.map do |i| 
        array << i[3]
      end
      if Employee.where(email: array.compact).present?
        email = Employee.where(email: array.compact).pluck(:email)
        array = array.join(",")
        return "File Is Invalid ,"" #{email} "" Contains invalid data"
      else
        rows.map do |i| 
          Employee.create(first_name: i[0], last_name: i[1], mobile_number: i[2].to_s.split(".")[0], email: i[3], employee_id: i[4], designation: i[5], ctc: i[6], date_of_birth: i[7], street: i[8], pincode: i[9], city: i[10], state: i[11], country: i[12])
        end   
        return "File Is Successfully Uploaded"        
      end   
    else
      return "Invalid Headers"
    end  	
  end

  def self.employee_report(params)
    employee_id = params["employee_id"]
    status = params["approval_status"]
    if status == "All" or status.nil?
      approval_status = [true, false, nil]
    elsif status == "Approved"
      approval_status = true
    else
      approval_status = [false, nil]
    end
    if employee_id.present?
      fromdate = params["from_date"]
      todate = params["to_date"]
      @employee_data = []
      emp_id = employee_id
      @emp_data = []
      @emp_data << Employee.find(emp_id).first_name
      date_wise_data = []
      (fromdate.to_date..todate.to_date).to_a.map do |date|
        time_sht = TimeSheet.where(date: date, employee_id: emp_id)
        if time_sht.present?
          if time_sht.pluck(:attendance_log).include?(false)
            emp_hours = "A"
            emp_cost = "A"
          else
            emp_hours = time_sht.where(approval_status: approval_status).pluck(:hours).compact.sum.round
            ctc = Employee.find(emp_id).ctc
            one_hour = (ctc/24)/8
            emp_cost = emp_hours * one_hour
          end
        else
          emp_hours = ""
          emp_cost = ""
        end
        date_wise_data << [date,emp_hours,emp_cost]
      end
      @emp_data << date_wise_data
      @employee_data << @emp_data
    else
      @employee_data = []
      fromdate = params[:from_date]
      todate = params[:to_date]
      employee_id = ProjectEmployee.pluck(:employee_id).uniq      
      employee_id.map do |emp_id|
        @emp_data = []
        @emp_data << Employee.find(emp_id).first_name
        date_wise_data = []
        (fromdate.to_date..todate.to_date).to_a.map do |date|
          time_sht = TimeSheet.where(date: date, employee_id: emp_id)
          if time_sht.present?
            if time_sht.pluck(:attendance_log).include?(false)
              emp_hours = "A"
              emp_cost = "A"
            else
              emp_hours = time_sht.where(approval_status: approval_status).pluck(:hours).compact.sum.round
              ctc = Employee.find(emp_id).ctc
              one_hour = (ctc/24)/8
              emp_cost = emp_hours * one_hour
            end
          else
            emp_hours = ""
            emp_cost = ""
          end
          date_wise_data << [date,emp_hours,emp_cost]
        end
        @emp_data << date_wise_data
        @employee_data << @emp_data
      end
    end
    return @employee_data, fromdate, todate
  end

  def self.employee_not_entered_timesheet
    admin_id =Role.find_by_name("Admin").id
    all_employees = User.where.not(role_id: admin_id).pluck(:employee_id).uniq
    if TimeSheet.where(date: Date.today).present?      
      employee_ids = TimeSheet.where(date: Date.today).pluck(:employee_id).uniq
      emp_ids = all_employees-employee_ids
      email_ids = Employee.where(id: emp_ids).pluck(:email)
    else
      email_ids = Employee.where(id: all_employees).pluck(:email)
    end
    unless email_ids.empty?
      email_ids.map do |email|
        DailyMailer.notification(email).deliver
      end
    end    
  end

  def self.get_data(report)
    report_type = report
    if report_type == "weekly"
      @dates = (Date.yesterday.beginning_of_week-1..Date.yesterday.end_of_week-1)
    elsif report_type == "monthly"
      @dates = ((Date.yesterday-1).beginning_of_month..(Date.yesterday-1).end_of_month)
    end
    if ProjectEmployee.present?
      @employee_data = []
      employee_id = ProjectEmployee.pluck(:employee_id).uniq
      employee_id.map do |emp_id|
        @emp_data = []
        @emp_data << Employee.find(emp_id).first_name
        date_wise_data = []
        @dates.map do |date|
          time_sht = TimeSheet.where(date: date, employee_id: emp_id, approval_status: true)
          if time_sht.present?
            if time_sht.pluck(:attendance_log).include?(false)
              emp_hours = "A"
              emp_cost = "A"
            else
              emp_hours = time_sht.pluck(:hours).compact.sum.round
              ctc = Employee.find(emp_id).ctc
              one_hour = (ctc/24)/8
              emp_cost = emp_hours  * one_hour
            end
          else
            emp_hours = ""
            emp_cost = ""
          end
          #date_wise_data << [date, emp_hours, emp_cost]
          date_wise_data << [emp_hours]
        end
        total = date_wise_data.flatten.map{|i| i.to_f}.sum.round
        @emp_data << date_wise_data
        @emp_data << total
        @employee_data << @emp_data.flatten
      end
    else
      @employee_data = nil
    end
    return @employee_data
  end

  def self.employee_pdf    
    result = Employee.get_data("weekly")

    p = Axlsx::Package.new
    ws = p.workbook.add_worksheet(:name => "Employee weekly Report")
    title = ws.styles.add_style(:b => true, :alignment=>{:horizontal => :center})

    ws.add_row ["Employee Utilization for the week #{(Date.yesterday.beginning_of_week-1).strftime('%a, %d-%b-%Y')} to #{(Date.yesterday.end_of_week-1).strftime('%a, %d-%b-%Y')}"], :style => title

    headers = ["Employee Name"]
    ((Date.yesterday.beginning_of_week-1)..(Date.yesterday.end_of_week-1)).map do |e|
      headers << e.to_date.strftime("%d-%b").to_s
    end
    headers << "Total"
    
    ws.add_row headers, :style => title
    result.each do |data|
      row = ws.add_row
      data.each do |val|
        row.add_cell val
      end
    end

    ws.merge_cells "A1:I1"
    path = "#{Rails.root}/public/weekly_employee_utilisation_report_#{Date.today.strftime('%d-%m-%Y')}.xlsx"    
    p.serialize(path)
    @user2={:email=> "poombavai.sivamani@altiussolution.com"}
    ProjectbaseMailer.report(@user2,path,type="weekly").deliver
  end  

  def self.monthly_pdf
    result = Employee.get_data("monthly")

    p = Axlsx::Package.new
    ws = p.workbook.add_worksheet(:name => "#{(Date.yesterday-1).strftime("%B-%Y").to_s}")
    title1 = ws.styles.add_style(:b => true, :alignment=>{:horizontal => :center}, :sz => 16)
    title2 = ws.styles.add_style(:b => true, :alignment=>{:horizontal => :center}, :sz => 14)

    ws.add_row ["Employee Utilization for the month #{(Date.yesterday-1).beginning_of_month.strftime('%a, %d-%b-%Y')} to #{(Date.yesterday-1).end_of_month.strftime('%a, %d-%b-%Y')}"], :style => title1

    headers = ["Employee Name"]
    (((Date.yesterday-1).beginning_of_month.to_date .. (Date.yesterday-1).end_of_month.to_date).to_a).map do |date|
        headers << date.strftime("%d")
      end
    headers << "Total"
    
    ws.add_row headers, :style => title2
    result.each do |data|
      row = ws.add_row
      data.each do |val|
        row.add_cell val
      end
    end

    ws.merge_cells "A1:I1"
    path = "#{Rails.root}/public/monthly_employee_utilisation_report_#{Date.today.strftime('%d-%m-%Y')}.xlsx"    
    p.serialize(path)
    @user2={:email=> "poombavai.sivamani@altiussolution.com"}
    ProjectbaseMailer.report(@user2,path,type="monthly").deliver
  end    

end

app/controllers/api/v1/employees_controller.rb
module Api
  module V1
    class EmployeesController < ApplicationController

      skip_before_action :check_session
      before_action :set_employee, only: [:show, :update, :destroy]
      before_action :require_login! ,:except=>[:employee_details]
      before_action :check_app_version
      skip_before_action :verify_authenticity_token

      respond_to :json

      def index
        #@employees = Employee.all
        aa = TimeSheet.where(approval_status: nil).pluck(:employee_id).uniq
        employees = Employee.all.map do |emp|
          if aa.include?emp.id
            emp.as_json.merge({:approval_status => false})
          else
            emp.as_json.merge({:approval_status => true})
          end
        end
        render json: employees
      end

      def show
        render json: @employee
      end

      def create
        @employee=Employee.new(employee_params)
        @employee.save
        render json: @employee
      end

      def update
        @employee.update(employee_params)
        render json: @employee
      end

      def destroy
        @employee.destroy
        render json: @employee
      end

      def employee_details
        employee=Employee.where(:email=>params[:email])
        if employee.present?
          employee1=Employee.where(:email=>params[:email],:status=>nil)
          if employee1.present?
            render json: employee1
          else
            render json: true #{"message"=>"already registered"} 
          end   
        else  
         render json: false#{"message"=>"Sorry this email is not registered"} 
        end
      end  

      def project_assign
        params.permit!
        #employee_id=User.find(params[:user_id]).employee_id
        project=ProjectEmployee.create(:project_id=>params[:project_id],:employee_id=>params[:employee_id])
        unless project["id"].nil?
          render json: true
        else
          render json: false
        end
      end  

      def unassigned_project
        employee = ProjectEmployee.where(:employee_id=>params["employee_id"])
        if employee.present?
          project = Project.where.not(:id=>employee.pluck(:project_id))
          render json: project
        else
          render json: Project.all
        end
      end  

      def assigned_project 
        employee=ProjectEmployee.where(:employee_id=>params["employee_id"])
        if employee.present?
          project=Project.where(:id=>ProjectEmployee.where(:employee_id=>params["employee_id"]).pluck(:project_id))
          render json: project
        else
          render json: false#Project.all
        end 
      end

      def image_upload
        ten=Time.now.strftime("%d-%m-%Y %H:%M:%S").to_s
        path = "public/#{ten}.png"
        img_binary = params[:message_log][:image].split(",")[1]
        File.open(path,"wb"){|pp| pp.write Base64.decode64(img_binary) }
        path=File.open(File.join(Rails.root,path))
        Employee.find(params[:message_log][:employee_id]).update(:image=>path) 
        render json: true
      end

      def require_login!
        return true if authenticate_token
        render json: { errors: [ { detail: "Access denied" } ] }, status: 401
      end

      private

      def check_app_version
        return true if params[:app_version].present? and AppVersion.last.version_no == params[:app_version]
        render json: { errors: [ { detail: "Access denied !! Check App Version" } ] }, status: 401
      end      

      def authenticate_token
        authenticate_with_http_token do |token, options|
          User.find_by(auth_token: token)
        end
      end

      def set_employee
        @employee = Employee.find(params[:id])
      end

      def employee_params
        params.require(:employee).permit(:first_name, :last_name, :mobile_number, :email, :employee_id, :designation, :date_of_birth, :street, :pincode, :city, :state, :country, :status)
      end

    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @employees = Employee.all
    
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    redirect_to employees_path
    #respond_with(@employee)
    flash[:notice]="Employee Successfully Created"
  end

  def update
    @employee.update(employee_params)
    redirect_to employees_path
    #respond_with(@employee)
    flash[:notice]="Employee Successfully Updated"
    #redirect_to :action=>"index"
    

  end

  def destroy
    @employee.destroy
    respond_with(@employee)
    flash[:notice]="Employee Successfully Deleted"
  end

  def import_employee
  params.permit!
  data=Employee.import_data(params)
  flash[:message]="#{data}"
  redirect_to :action=>"index"
  end  

  def employee_report
    #byebug
    @employees = Employee.all
    @projects = Project.all
    if params["commit"] == "Get Report"
      @working_days = params["working_days"]
      @employee_reports = Employee.employee_report(params)
    else
      @working_days = 7
      from_date = 1.week.ago.strftime("%Y-%m-%d")
      to_date = Date.today.strftime("%Y-%m-%d")
      @employee_reports = Employee.employee_report("employee_id": nil, "from_date": from_date, "to_date": to_date)
    end
  end


  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :mobile_number, :email, :employee_id, :designation, :ctc, :date_of_birth, :street, :pincode, :city, :state, :country, :status)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<center><h3>Editing Employee</h3></center>

<div style="float: left; margin-left: 300px;">

<%= link_to 'Show', @employee ,:class=>"btn btn-primary" %>
<%= link_to 'Back', employees_path ,:class=>"btn btn-danger" %>

</div>
<%= render 'form', employee: @employee %>

app/views/employees/employee_report.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css"/>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script> -->

<div class="container-fluid">
  <div class="col-md-12 row">      
    <div class="col-md-2">
      <label>Employee Name</label>
    </div>
    <div class="col-md-2">
      <label>Status</label>
    </div>
    <div class="col-md-2">
      <label>From Date</label>
    </div>
    <div class="col-md-2">
      <label>To Date</label>
    </div>
    <div class="col-md-2">
      <label>Working days</label>
    </div>
  </div>
  <%= form_for(Employee.new, url: employee_report_path) do |f| %>
    <div class="col-md-12 row">      
      <div class="col-md-2">
        <% if @employee_reports[0].count == 1 %>
          <% @employee_reports[0].each do |employee| %>
            <%= select_tag "employee_id", options_for_select(@employees.map { |obj| [obj['first_name'], obj['id']] },:selected=>Employee.where(first_name: employee[0]).ids[0]), class: "form-control", prompt: "All"%> 
          <% end %>
        <% else %>
          <%= select_tag "employee_id", options_from_collection_for_select(@employees, "id", "first_name"), {prompt: "All", class: "form-control"} %>
        <% end %>
      </div>
      <div class="col-md-2">
        <% if params["approval_status"].present? %>
          <%= select_tag "approval_status", options_for_select(["All", "Approved", "Not Approved"], params["approval_status"]), {class: "form-control"} %>
        <% else %>
          <%= select_tag "approval_status", options_for_select(["All", "Approved", "Not Approved"], "All"), {class: "form-control"} %>
        <% end %>
      </div>
      <div class="col-md-2">
      	<input type="text" name="from_date" class="form-control" id="dt1" required="true" readonly="true" value="<%= @employee_reports[1].to_date.strftime('%d-%m-%Y') %>" >
      </div>
      <div class="col-md-2">
      	<input type="text" name="to_date" class="form-control" id="dt2" required="true" readonly="true" value="<%= @employee_reports[2].to_date.strftime('%d-%m-%Y') %>">
      </div>
      <div class="col-md-2">
        <input type="text" name="working_days" class="form-control" required="true" value="<%= @working_days %>">
      </div>
      <div class="col-md-2">
        <%= f.submit 'Get Report', class: "btn btn-primary", id: "report", "data-disable-with": false %>&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Back', clients_dashboard_path, :class=>"btn btn-danger" %>
      </div>
    </div>

  <% end %>  

  <% if @employee_reports.present? %>
    <% from_date = @employee_reports[1].to_date %>
    <% to_date = @employee_reports[2].to_date %>
    <% over_all_hours = @working_days.to_f * 8 %>

  	<div class="container-fluid ">
      <div class="row">
        <div class="col-md-12">
  	      <center><h3>Employee Utilization Report from <%= from_date.strftime("%a, %d-%m-%Y") %> to <%= to_date.strftime("%a, %d-%m-%Y") %> </h3></center>
        </div>
      </div>
      <!-- <%# unless params["data"].present? %>
        <div style="float: right; margin: 5px 65px;">
          <%#= link_to 'Back', :back, :class=>"btn btn-danger" %>
        </div>
      <%# end %> -->

  	  <div class="col-md-12 box table-responsive">
      	<table class="table table-striped table-bordered" id="table_id">
          <thead class="table_head">
            <tr>
              <th><center>S.No</center></th>
              <th><center>Employee</center></th>
              <% hash = {} %>
              <% (from_date..to_date).to_a.each do |date| %>
                <th><center><%= date.strftime("%d %b") %></center></th>
                <% hash[date] = [] %>
              <% end %>
              <th><center>Total(Hrs)</center></th>
              <th><center>Utilization %</center></th>
            </tr>
          </thead>
          <tbody> 
            <% grand_total = [] %>
            <% s=1 %>            
          	<% @employee_reports[0].each do |employee| %>
        	    <tr>
                <% @total = [] %>
          	  	<td align="right"><%= s %></td>          	  	
          	  	<td><%= employee[0] %></td>
                <% employee[1].each do |emp| %>
                  <td align="right">                    
                    <% if emp[1].present? %>
                      <% if emp[1].class == String %>
                        <%= emp[1] %>
                      <% else %>
                        <%= emp[1].round %>
                        <% hash[emp[0]] << emp[1] %>
                        <% @total << emp[1].round %>
                      <% end %>
                    <% else %>
                    <% end %>
                  </td>
                <% end %>
                <% tot =  @total.sum %>
                <td align="right"><%= tot %></td>
                <td align="right"><%= ((tot/over_all_hours)*100).round(2) %></td>
              </tr>
        	    <% s+=1 %>
            <% end %>
            <tr style="background-color: #9c9c9c">
              <td align="right"><b><%= @employee_reports[0].count+1 %></b></td>
              <td><b>Total</b></td>
              <% total = [] %>
              <% hash.each do |k, v| %>
                <td align="right"><b><%= tot = v.map { |e| e.to_f }.sum.round %></b></td>
                <% total << tot %>
              <% end %>              
              <td align="right"><b><%= total.sum.round %></b></td>
              <% grand_total << total.sum %>
              <% grand_overall_hours = @employee_reports[0].count.to_f * over_all_hours %>
              <% utilization1 = (grand_total.sum.to_f/grand_overall_hours)*100 %>
              <td align="right"><%= utilization1.round(2) %></td>
            </tr>
          </tbody>
      	</table>
      </div>
  	</div>
  <% end %>
</div>


<script type="text/javascript">
  $(document).ready(function () {
    $("#dt1").datepicker({
      dateFormat: "dd-mm-yy",
      maxDate:'+0d',
      onSelect: function (date) {
        var dt2 = $('#dt2');
        var startDate = $(this).datepicker('getDate');
        var minDate = $(this).datepicker('getDate');
        dt2.datepicker('setDate', minDate);
        startDate.setDate(startDate.getDate() + 60);        
        dt2.datepicker('option', 'minDate', minDate);
        dt2.datepicker('option', 'maxDate', 0);
        //dt2.datepicker('option', 'maxDate', '0');
      }
    });
    $('#dt2').datepicker({
      dateFormat: "dd-mm-yy",
      maxDate:'+0d'
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function() { 
    $("#dt1").each(function(ev) {
      if(!$(this).val()) { 
        $(this).attr("placeholder", "dd-mm-yy");
      }
    });
    $("#dt2").each(function(ev) {
      if(!$(this).val()) { 
        $(this).attr("placeholder", "dd-mm-yy");
      }
    });
  });
</script>

app/views/employees/index.html.erb
<div class="container-fluid">
  <center><p id="notice" style="color:red;"><%= flash[:message] %></p></center>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Import Empolyee Details</button>  
  <%= link_to "Sample Csv Format", clients_sample_csv_path(format: "csv") ,:class=>"btn btn-primary"%>
  <%#= link_to 'Reports', employee_report_path, :style=>"color:#fff;float:right;margin-right:10px;",:class=>"btn btn-primary" %> &nbsp;
  <%= link_to 'Add Employee', new_employee_path ,:style=>"color:#fff;float:right;margin-right:10px;",:class=>"btn btn-primary" %> &nbsp; 

  <br>

  <div class="row container-fluid" style="margin-top: 40px;">
    <center><h3><b>Employees List<b></h3></center>
    
    <div class="col-md-12 box">
      <table class="table table-striped table-bordered" id="table_id">
        <thead class="table_head">
          <tr>
            <th>S_No</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Mobile number</th>
            <th>Email</th>
            <th>Employee ID</th>
            <th>Designation</th>
            <th>Date of birth</th>
            <th>Action</th>
            
            <!-- <th>Delete</th> -->
          </tr>
        </thead>
        <tbody>
          <% s_no=1 %>
          <% @employees.each do |employee| %>
            <tr>
              <td style="text-align:right;"><%=s_no%></td>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td style="text-align:right;"><%= employee.mobile_number %></td>
              <td><%= employee.email %></td>
              <td><%= employee.employee_id %></td>
              <td><%= employee.designation %></td>
              <td style="text-align:center;"><%= employee.date_of_birth %></td>
              <td><center><%= link_to 'View', employee %>&nbsp;|&nbsp;<%= link_to 'Edit', edit_employee_path(employee) %></center></td>
              <!-- <td><center><!%= link_to '', employee, method: :delete, data: { confirm: 'Are you sure?' },:class=>"fa fa-trash-o" %></center></td> -->
            </tr>
            <% s_no += 1 %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #286090;color: white;height:55px;">
        <center><h4 class="modal-title" id="exampleModalLabel">Import Contacts for Company</h4></center>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for Employee.new,:url=>{:controller=>"employees",:action=>"import_employee"} do |i| %>
          Select File : <%= i.file_field :address,required:true,:class=>"form-control",:id=>"browse" %>
      </div>
      <div class="modal-footer">
        <%= i.submit "Upload", :class=>"btn btn-primary"%>
        <% end %>
        <label class="btn btn-secondary" data-dismiss="modal">Cancel</label>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  document.getElementById("browse").onchange = function() {
    var fileName = this.value;
    var fileExten = fileName.substr(fileName.length - 4);
    var fileExtension=fileExten.toLowerCase()
    if (fileExtension == ".csv") {
        //alert("That ain't no .csv file!");
    }
    else if (fileExtension == ".xls"){

    }
    else if (fileExtension == ".xlsx"){
    }
    else {
     alert("Only accept CSV or XLS"); 
    }
    }

}
</script>