config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  get 'logout' => 'sessions#destroy'
  get 'detailed_report' => 'projects#detailed_report'
  get 'employee_report' => 'employees#employee_report'
  post 'employee_report' => 'employees#employee_report'
  get 'project_report' => 'projects#project_report'
  post 'project_report' => 'projects#project_report'  
  get 'users/old_password_check'
  get 'users/change_password'
  post 'users/change_password_update'
  get 'projects/project_active_status'
  get 'users/new_password'
  post 'users/set_new_password'
  get 'clients/sample_csv'
  get 'sessions/new'
  post 'employees/import_employee'
  get 'clients/dashboard'
  
  resources :sessions
  resources :users  
  resources :projects
  resources :employees
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'is_absent' => 'time_sheets#is_absent'
      get 'time_sheets/date'
      get 'employees/assigned_project'
      get 'users/forgot_password'
      get 'projects/approval_status'
      get 'time_sheets/time_approval_status'
      post 'employees/image_upload'
      get 'logs/call_index'
      get 'logs/call_show'
      post 'logs/call_create'
      put 'logs/call_update'
      get 'logs/message_index'
      get 'logs/message_show'
      post 'logs/message_create'
      put 'logs/message_update'
      get 'time_sheets/project_working_hours'
      get 'clients/client_contacts'
      get 'clients/client_projects'
      get 'employees/unassigned_project'
      get 'time_sheets/cost_estimate'
      get 'contacts/client_contacts'
      get 'projects/project_employee'
      get 'time_sheets/employee_time_sheet'
      get 'employees/project_assign'
      get 'users/user_registration'
      get 'users/login_validation'
      get 'employees/employee_details'	
      resources :contacts
      resources :users	
      resources :employees
      resources :clients
      resources :projects
      resources :roles
      resources :time_sheets
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :projects, dependent: :destroy
	has_many :contacts, dependent: :destroy
	accepts_nested_attributes_for :contacts, allow_destroy: true
   validates_uniqueness_of :name
   validates :name, uniqueness: { case_sensitive: false}

def self.file_generate
     CSV.generate do |csv|
      csv << ["first_name","last_name","mobile_number","email","employee_id","designation","ctc","date_of_birth","street","pincode","city","state","country"]
    end
  end

end

app/controllers/api/v1/clients_controller.rb
module Api
  module V1

    class ClientsController < ApplicationController
      skip_before_action :check_session
      before_action :set_Client, only: [:show, :update, :destroy]
      before_action :require_login!  
      before_action :check_app_version
      skip_before_action :verify_authenticity_token
      
      respond_to :json

      def index
        @clients = Client.all
        render json: @clients
      end

      def show
        render json: @client
      end

      def create
        @client=Client.new(Client_params)
        @client.save
        render json: @client
      end

      def update
        @client.update(client_params)
        render json: @client
      end

      def destroy
        @client.destroy
        render json: @client
      end

      def client_projects
        client=Client.all.as_json(include: :projects)
        render json: client
      end
      
      def client_contacts
        client=Client.find(params[:client_id]).contacts
        render json: client
      end      

      def require_login!
        return true if authenticate_token
        render json: { errors: [ { detail: "Access denied" } ] }, status: 401
      end

      private

      def check_app_version
        return true if params[:app_version].present? and AppVersion.last.version_no == params[:app_version]
        render json: { errors: [ { detail: "Access denied !! Check App Version" } ] }, status: 401
      end

      def authenticate_token
        authenticate_with_http_token do |token, options|
          User.find_by(auth_token: token)
        end
      end
      
      def set_Client
        @client = Client.find(params[:id])
      end

      def Client_params
        params.require(:client).permit(:name, :street, :pincode, :city, :state, :country)
      end
    end

  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @clients = Client.all
    respond_with(@clients)
  end

  def show
    respond_with(@client)
  end

  def new
    @client = Client.new
    respond_with(@client)
  end

  def edit
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      #respond_with(@client)

      redirect_to clients_path
      flash[:notice]=" Client Successfully Created"
    else
      render "new"
    end
  end  

  def update
    if @client.update(client_params)
      redirect_to clients_path
       #respond_with(@client)
       flash[:notice]="Client Successfully Updated"
    else
     render "new"
    end  
  end

  def destroy
    @client.destroy
    respond_with(@client)
    flash[:notice]="Client Successfully Deleted"
  end

  def sample_csv
     respond_to do |format|
      format.html
      format.csv { send_data Client.file_generate }
     end
  end  

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :street, :pincode, :city, :state, :country, contacts_attributes: [:id,:name,:designation,:email,:telephone_number,:mobile_number,:client_id, :_destroy])
    end
end















    

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="container-fluid">
  
<div class="container ">

    <div class="box">


<%= nested_form_for client do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="col-md-6">
    <%= form.label :name %><span style="color:red">*</span>
    <%= form.text_field :name, id: :client_name  ,:class=>"form-control",required:true%>
  </div>

  <div class="col-md-6">
    <%= form.label :street %>
    <%= form.text_field :street, id: :client_street  ,:class=>"form-control" %>
  </div>
  </div>

  <div class="row">
  <div class="col-md-6">
    <%= form.label :pincode %>
    <%= form.text_field :pincode, id: :client_pincode  ,:class=>"form-control mobile_number"%>
  </div>

  <div class="col-md-6">
    <%= form.label :city %>
    <%= form.text_field :city, id: :client_city  ,:class=>"form-control"%>
  </div>
  </div>

  <div class="row">
  <div class="col-md-6">
    <%= form.label :state %>
    <%= form.text_field :state, id: :client_state  ,:class=>"form-control"%>
  </div>

  <div class="col-md-6">
    <%= form.label :country %>
    <%= form.text_field :country, id: :client_country  ,:class=>"form-control"%>
  </div>
</div>

<%= form.fields_for :contacts, validate:true do |task_form| %>

  <div style="text-align:center;color:red;" id="errmsg">
    </div> 

<div class="row">
<!-- <div class="box">
 -->
  <br>
     <div class="col-md-2">
       <!--%= task_form.label :name %-->

       <%= task_form.text_field :name, :class=>"form-control" ,required:true, placeholder: "name"%>
    </div>
    
    <div class="col-md-2">
       <!--%= task_form.label :designation %-->

       <%= task_form.text_field :designation, :class=>"form-control" ,required:true, placeholder: "role"%>
    </div>
     
     <div class="col-md-2">
       <!--%= task_form.label :email %-->

       <%= task_form.text_field :email, :class=>"form-control ", placeholder: "email" %>
    </div>

    <div class="col-md-2">
       <!--%= task_form.label :telephone_number,"Telephone-no" %-->

       <%= task_form.text_field :mobile_number,:class=>"form-control mobile_number" ,required:true , placeholder: "mobile-no"%>
    </div>
 

     <div class="col-md-2">
       <!--%= task_form.label :mobile_number,"Mobile-no" %-->

       <%= task_form.text_field :telephone_number,:class=>"form-control mobile_number", placeholder: "teleph-no" %>
    </div>

    <div id="errmsg">
    </div>
     
    <div class="col-md-2">
       <%= task_form.link_to_remove "<i class 'fa fa-trash-o'></i>".html_safe,:class=>"btn btn-danger fa fa-trash-o" ,title:"Remove"%>
      <!--%= task_form.link_to_remove "<i class 'fa fa-trash-o'></i>".html_safe, :class=>"btn btn-danger"%-->
     </div>
    
<!--   </div>  
 -->  </div>
<% end %>

<br>

<div class="row">
      <div  class="col-md-12"> <%= form.link_to_add "Add a Contact", :contacts,:class=>"btn btn-primary", :style=>"margin-top: 20px;"%></div>
         <div class="col-md-2 col-md-offset-9">
         <%= form.submit  :class=>"btn btn-success"%>
         </div>
      <!--/div-->
</div>
<% end %>

</div>
</div>
</div>

<script type="text/javascript">

$(document).on('nested:fieldAdded', function(event){
 
  var field = event.field;
  var IField = field.find('.mobile_number');
  var IsField = field.find('.tele_number');

 $(".mobile_number").keypress(function (e) {
      
     
     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
     
        $("#errmsg").html("Digits Only" ).show().fadeOut("slow");
               return false;
       }
     });
  })


</script>



<script type="text/javascript">
  $(".mobile_number").keypress(function (e) {
  
     
     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
     
        //$("#errmsg").html("Digits Only" ).show().fadeOut("slow");
               return false;
       }
     });
 
</script>

app/views/clients/dashboard.html.erb
<style>

.glyphicon{
  color: #E96E28;
  font-size: 20px;
}
a{
  text-decoration: none;
}
</style>

<div class="container-fluid">
  <div class="row">
    <center><h2><b>ALTIUS PROJECT MANAGEMENT</b></h2></center>
    <br>
  </div>
  <div class="row">  
    <div class="col-md-12 ">

      <div class="col-sm-6 col-sm-offset-4">
        <div class="col-md-12">
          <span class="glyphicon glyphicon-triangle-right"><a href="/clients">Clients</a></span>
        </div>
        <div class="col-md-12">
          <span class="glyphicon glyphicon-triangle-right"><a href="/projects">Projects</a></span>
        </div>
        <div class="col-md-12">
          <span class="glyphicon glyphicon-triangle-right"><a href="/employees">All&nbsp;Employees</a></span>
        </div>
        <div class="col-md-12">
          <span class="glyphicon glyphicon-triangle-right"><%= link_to 'Employee Utilization Reports', employee_report_path(:data=>"dashboard")%></span>
        </div>
        <div class="col-md-12">
          <span class="glyphicon glyphicon-triangle-right"><%= link_to 'Project Cost Report', project_report_path(:data=>"dashboard")%></span>
        </div>
      </div>

    </div>
  </div>
</div>

 <!--  <div class="row">
    <div class="col-md-4">
      <div  class="jumbotron text-center">
        <h1><!%= Client.count%></h1>
        <a href="/clients">Clients</a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="jumbotron text-center">
        <h1><!%= Project.count%></h1>
        <a href="/Projects">Projects</a>
      </div>
    </div>
    <div class="col-md-4">
      <div class="jumbotron text-center">
        <h1><!%= Employee.count%></h1>
        <a href="/employees">Employees</a>
      </div>
    </div>
  </div> -->

<!--   <div class="row">
  <br>
    <div class="col-md-12">
      <div class="col-sm-6 col-sm-offset-4">
        <div class="col-md-4">
          <!%= link_to 'Clients Reports', employee_report_path,:class=>"btn btn-primary"%>
        </div>
        <div class="col-md-4">
          <!%= link_to 'Projects Reports', project_report_path,:class=>"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div> -->

app/views/clients/edit.html.erb
<center><h3>Editing Client</h3></center>

<div style="float: right; margin: 5px 65px;">

<%= link_to 'Show', @client ,:class=>"btn btn-danger" %>
<%= link_to 'Back', client_path ,:class=>"btn btn-success" %>

</div>
<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<div class="container-fluid">
  <%= link_to 'Add Client', new_client_path ,:style=>"color:#fff;float:right;margin-right:10px;",:class=>"btn btn-primary" %>
  <br>

  <div class="row container-fluid " style="margin-top: 40px;">
    <center><h3><b>Clients<b></h3></center>
    
    <div class="col-md-12 box">
      <table class="table table-striped table-bordered" id="table_id">
        <thead class="table_head">
          <tr>
            <th>S_no</th>
            <th>Name</th>
            <th>Street</th>
            <th>Pincode</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Action</th>
            <!-- <th>Delete</th> -->
          </tr>
        </thead>
        <tbody>
          <% s=1 %>
          <% @clients.each do |client| %>
            <tr>
              <td style="text-align:right;"><%= s%></td>
              <td><%= client.name %></td>
              <td><%= client.street %></td>
              <td style="text-align:right;"><%= client.pincode %></td>
              <td><%= client.city %></td>
              <td><%= client.state %></td>
              <td><%= client.country %></td>
              <td><%= link_to 'View', client %>&nbsp;|&nbsp;<%= link_to 'Edit', edit_client_path(client) %></td>
              <!-- <td><center><!%= link_to '', client, method: :delete, data: { confirm: 'Are you sure?' },:class=>"fa fa-trash-o" %></center></td> -->
            </tr>
            <% s +=1 %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<center><h3>New Client</h3></center>

<div style="float: right; margin: 5px 65px;">

<%= link_to 'Back', clients_path ,:class=>"btn btn-danger"%>

</div>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<div class="container ">
<div class="row">
  <center><h3>Client Details</h3></center>
</div>
<div style="float: right;">
  <%= link_to  'Edit', edit_client_path(@client) ,:class=>"btn btn-success" %>
  <%= link_to 'Back', clients_path,:class=>"btn btn-danger" %>
</div>

<div class="col-md-12 box">
  <div class="row">
    <div class="col-md-6">
      <div class="fontcolr">Name </div>
      <div><%= @client.name %></div>
    </div>
    <div class="col-md-6">
      <div class="fontcolr">Street</div>
        <div><%= @client.street %></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="fontcolr"> Pin Code </div>
      <div><%= @client.pincode %></div>
    </div>
    
    <div class="col-md-6">
      <div class="fontcolr">City </div>
      <div><%= @client.city %></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="fontcolr"> State</div>
      <div><%= @client.state %></div>
    </div>

    <div class="col-md-6">
      <div class="fontcolr">Country </div>
      <div><%= @client.country %></div>
    </div>
    </div>
    


  <table class="table">


<%if @client.contacts.present?%>
   <tr style="background: #286090;color:white;text-align:center">
   <th>S.No</th>
   <th>Name</th>
   <th>Role</th>
   <th>Email</th>
   <th style="text-align: right">Mobile-No</th> 
   <th style="text-align: right">Telephone-No</th>
   <!--th>Edit</th> 
   <th>Delete</th-->
   </tr>
   <%sno=1%>
     <%@client.contacts.map do |contact|%>
     <tr>
     <td><%=sno%></td><%sno=sno+1 %>
     <td><%=contact.name%></td>
     <td><%=contact.designation%></td>
     <td><%=contact.email%></td>
     <td style="text-align: right"><%=contact.mobile_number%></td>
     <td style="text-align: right"><%=contact.telephone_number%></td>
    </tr>
    <%end%>
<%end%>