config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  get 'logout' => 'sessions#destroy'
  get 'detailed_report' => 'projects#detailed_report'
  get 'employee_report' => 'employees#employee_report'
  post 'employee_report' => 'employees#employee_report'
  get 'project_report' => 'projects#project_report'
  post 'project_report' => 'projects#project_report'  
  get 'users/old_password_check'
  get 'users/change_password'
  post 'users/change_password_update'
  get 'projects/project_active_status'
  get 'users/new_password'
  post 'users/set_new_password'
  get 'clients/sample_csv'
  get 'sessions/new'
  post 'employees/import_employee'
  get 'clients/dashboard'
  
  resources :sessions
  resources :users  
  resources :projects
  resources :employees
  resources :clients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'is_absent' => 'time_sheets#is_absent'
      get 'time_sheets/date'
      get 'employees/assigned_project'
      get 'users/forgot_password'
      get 'projects/approval_status'
      get 'time_sheets/time_approval_status'
      post 'employees/image_upload'
      get 'logs/call_index'
      get 'logs/call_show'
      post 'logs/call_create'
      put 'logs/call_update'
      get 'logs/message_index'
      get 'logs/message_show'
      post 'logs/message_create'
      put 'logs/message_update'
      get 'time_sheets/project_working_hours'
      get 'clients/client_contacts'
      get 'clients/client_projects'
      get 'employees/unassigned_project'
      get 'time_sheets/cost_estimate'
      get 'contacts/client_contacts'
      get 'projects/project_employee'
      get 'time_sheets/employee_time_sheet'
      get 'employees/project_assign'
      get 'users/user_registration'
      get 'users/login_validation'
      get 'employees/employee_details'	
      resources :contacts
      resources :users	
      resources :employees
      resources :clients
      resources :projects
      resources :roles
      resources :time_sheets
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  has_many :project_employees, dependent: :destroy
  has_many :time_sheets, dependent: :destroy
  validates_uniqueness_of :name

  def self.get_data(report)
    report_type = report
    if report_type == "weekly"
      @dates = (Date.yesterday.beginning_of_week-1..Date.yesterday.end_of_week-1)
    elsif report_type == "monthly"
      @dates = ((Date.yesterday-1).beginning_of_month..(Date.yesterday-1).end_of_month)
    end
    if Project.where(:status => true).present?
      tot_data1, tot_data2, tot_data3, tot_data4 = [], [], [], []
      @project_over_all_data = []
      Project.where(:status => true).map do |project|
        over_all_project_hours = []    
        over_all_project_cost = []
        project_hours = []
        project_cost = []
        if TimeSheet.where(:approval_status => true, :project_id => project["id"]).present?
          employee_group = TimeSheet.where(:approval_status => true, :project_id => project["id"]).group_by(&:employee_id)
          employee_group.map do |employee_id,time_sheet|
            ctc = Employee.find(employee_id).ctc
            time = time_sheet.pluck(:hours).sum
            one_hour = (ctc/24)/8
            over_all_project_hours << time
            over_all_project_cost << (time*one_hour)
          end
          time_sheets = TimeSheet.where(:date => @dates, :approval_status => true, :project_id => project["id"])
          if time_sheets.present?
           employee_group = time_sheets.group_by(&:employee_id)
            employee_group.map do |employee_id,time_sheet|
              ctc = Employee.find(employee_id).ctc
              time = time_sheet.pluck(:hours).sum
              one_hour = (ctc/24)/8
              project_hours << time
              project_cost << (time*one_hour)
            end 
          else
            project_hours << nil
            project_cost << nil
          end
        end
        data1 = project_hours.compact.sum.round == 0 ? nil : project_hours.compact.sum.round
        data2 = project_cost.compact.sum.round == 0 ? nil : project_cost.compact.sum.round
        data3 = over_all_project_hours.compact.sum.round == 0 ? nil : over_all_project_hours.compact.sum.round
        data4 = over_all_project_cost.compact.sum.round == 0 ? nil : over_all_project_cost.compact.sum.round

        tot_data1 << data1
        tot_data2 << data2
        tot_data3 << data3
        tot_data4 << data4
        
        @project_over_all_data << [project["name"], data1, data2, data3, data4]
      end
      @project_over_all_data << ["Total", tot_data1.compact.sum, tot_data2.compact.sum, tot_data3.compact.sum, tot_data4.compact.sum]
    else
      @project_over_all_data = nil
    end
    return @project_over_all_data
  end

  def self.project_pdf    
    result = Project.get_data("weekly")
    path = "#{Rails.root}/public/weekly_employee_utilisation_report_#{Date.today.strftime('%d-%m-%Y')}.csv"
    CSV.open(path, "wb") do |csv|
      csv << ["Project Cost Report for the week #{(Date.yesterday.beginning_of_week-1).strftime('%a, %d-%b-%Y')} to #{(Date.yesterday.end_of_week-1).strftime('%a, %d-%b-%Y')}"]
      csv << ["Project Name", "Hours (Past week)", "Cost (Past week)", "Overall Hours (Till date)", "Overall Cost (Till date)"]
      result.map do |data|
        csv << data
      end
    end
    @user2={:email=> "poombavai.sivamani@altiussolution.com"}
    ProjectbaseMailer.project_report(@user2,path,type="weekly").deliver
  end  

  def self.monthly_pdf
    result = Project.get_data("monthly")
    path = "#{Rails.root}/public/monthly_project_cost_report_#{Date.today.strftime('%d-%m-%Y')}.csv"
    CSV.open(path, "wb") do |csv|
      csv << ["Projects Cost Report for the month #{(Date.yesterday-1).beginning_of_month.strftime('%a, %d-%b-%Y')} to #{(Date.yesterday-1).end_of_month.strftime('%a, %d-%b-%Y')}"]
      csv << ["Project Name", "Hours (Past week)", "Cost (Past week)", "Overall Hours (Till date)", "Overall Cost (Till date)"]
      result.map do |data|
        csv << data
      end
    end
    @user2={:email=> "poombavai.sivamani@altiussolution.com"}
    ProjectbaseMailer.project_report(@user2,path,type="monthly").deliver
  end

  def self.project_report(params)  	
  	if params["project"]["id"].present? 

  	  project = Project.find(params["project"]["id"])
      @project_over_all_data, over_all_project_hours, over_all_project_cost, project_hours, project_cost = [], [], [], [], []
  	  timesht = TimeSheet.where(:project_id => project["id"])
  	  if timesht.present?
  	    employee_group = timesht.group_by(&:employee_id)
  	    employee_group.map do |employee_id,time_sheet|
  	  	  ctc = Employee.find(employee_id).ctc
  	  	  time = time_sheet.pluck(:hours).sum
  	  	  one_hour = (ctc/24)/8
  	  	  over_all_project_hours << time
  	  	  over_all_project_cost << (time*one_hour)
  	    end
        timesheets = timesht.where(:date => params["from_date"] .. params["to_date"])
        if timesheets.present?
      	  employee_group = timesheets.group_by(&:employee_id)
      	  employee_group.map do |employee_id,time_sheet|
      	    ctc = Employee.find(employee_id).ctc
      	    time = time_sheet.pluck(:hours).sum
      	    one_hour = (ctc/24)/8
      	    project_hours << time
            project_cost << (time*one_hour)
          end 
        else
      	  project_hours << 0
          project_cost << 0 
        end  
      end

      data1 = project_hours.compact.sum.round == 0 ? nil : project_hours.compact.sum.round
      data2 = project_cost.compact.sum.round == 0 ? nil : project_cost.compact.sum.round
      data3 = over_all_project_hours.compact.sum.round == 0 ? nil : over_all_project_hours.compact.sum.round
      data4 = over_all_project_cost.compact.sum.round == 0 ? nil : over_all_project_cost.compact.sum.round

      @project_over_all_data << [project["name"], data1, data2, data3, data4]

  	else

  	  if Project.where(:status => true).present?
  	  	@project_over_all_data = []
      	Project.where(:status => true).map do |project|
          over_all_project_hours = []
          over_all_project_cost = []
          project_hours = []
          project_cost = []
          timesht = TimeSheet.where(:project_id => project["id"])
          if timesht.present?
            employee_group = timesht.group_by(&:employee_id)
            employee_group.map do |employee_id,time_sheet|
              ctc = Employee.find(employee_id).ctc
              time = time_sheet.pluck(:hours).sum
              one_hour = (ctc/24)/8
              over_all_project_hours << time
              over_all_project_cost << (time*one_hour)
            end
            timesheets = timesht.where(:date => params["from_date"] .. params["to_date"]) 
            if timesheets.present?
              employee_group = timesheets.group_by(&:employee_id)
              employee_group.map do |employee_id,time_sheet|
              	ctc = Employee.find(employee_id).ctc
                time = time_sheet.pluck(:hours).sum
                one_hour = (ctc/24)/8
                project_hours << time
                project_cost << (time*one_hour)
              end 
            else
			        project_hours << 0
              project_cost << 0 
            end  
          end

          data1 = project_hours.compact.sum.round == 0 ? nil : project_hours.compact.sum.round
          data2 = project_cost.compact.sum.round == 0 ? nil : project_cost.compact.sum.round
          data3 = over_all_project_hours.compact.sum.round == 0 ? nil : over_all_project_hours.compact.sum.round
          data4 = over_all_project_cost.compact.sum.round == 0 ? nil : over_all_project_cost.compact.sum.round

          @project_over_all_data << [project["name"], data1, data2, data3, data4]
          
      	end
      end

    end

    return @project_over_all_data
  end

end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApplicationController

      skip_before_action :check_session
      before_action :set_project, only: [:show, :update, :destroy]
      before_action :require_login!
      before_action :check_app_version
      skip_before_action :verify_authenticity_token

      respond_to :json

      def index
        result = []
        projects = Project.where(status: true)
        project_ids = TimeSheet.where(approval_status: nil).pluck(:project_id).uniq
        projects.map do |project|
          if project.project_employees.present?
            if project_ids.include?project.id
              result << project.as_json.merge({is_assigned: true, :approval_status => false})
            else
              result << project.as_json.merge({is_assigned: true, :approval_status => true})
            end
          else
            result << project.as_json.merge({is_assigned: false, :approval_status => true})
          end
        end
        render json: result
      end

      def show
        render json: @project
      end

      def create
        @project=Project.new(project_params)
        @project.save
        render json: @project
      end

      def update
        @project.update(project_params)
        render json: @project
      end

      def destroy
        @project.destroy
        render json: @project
      end

      def project_employee
        data=ProjectEmployee.where(:project_id=>params[:project_id])
        if data.present?
          employee=Employee.where(:id=>data.pluck(:employee_id))
          render json: employee
        else
          render json: []
        end 
      end  

      def require_login!
        return true if authenticate_token
        render json: { errors: [ { detail: "Access denied" } ] }, status: 401
      end

      def approval_status
        TimeSheet.where(:project_id=>params["project_id"]).update(:approval_status=>true)
        render json: true
      end
      
      private

      def check_app_version
        return true if params[:app_version].present? and AppVersion.last.version_no == params[:app_version]
        render json: { errors: [ { detail: "Access denied !! Check App Version" } ] }, status: 401
      end      

      def authenticate_token
        authenticate_with_http_token do |token, options|
          User.find_by(auth_token: token)
        end
      end

      def set_project
        @project = Project.find(params[:id])
      end

      def project_params
        params.require(:project).permit(:name, :budget, :client_id)
      end

    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to projects_path
    #respond_with(@project)
  end

  def update
    @project.update(project_params)
    redirect_to projects_path
    #respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  def project_active_status
    params.permit!
    Project.find(params["id"]).update(status: params["status"])
    redirect_to projects_path
    #Project.find(params["id"]).update(status: params["status"])
  end  

  def project_report
    @projects = Project.all
    if params["commit"] == "Get Report"
      @from_date = params["from_date"]
      @to_date = params["to_date"]
      @project_reports = Project.project_report(params)
    else
      @from_date = 1.week.ago.strftime("%Y-%m-%d")
      @to_date = Date.today.strftime("%Y-%m-%d")
      @project_reports = Project.project_report("project" => {"id" => ""}, "from_date": @from_date, "to_date": @to_date)
    end
  end

  def detailed_report
    project = Project.find_by(:name => params[:name])
    time_sheet = TimeSheet.where(:project_id => project.id)
    employee_time_sheets = time_sheet.group_by(&:employee_id)
    @employee_details = employee_time_sheets.map do |k, v|
      employee = Employee.find(k)
      ctc = employee.ctc
      one_hour = (ctc/24)/8
      time = v.pluck(:hours).compact.sum
      {
        :employee_name => employee.first_name,
        :hours => v.pluck(:hours).compact.sum,
        :cost => (time*one_hour)
      }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :budget, :client_id)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="container-fluid">
  
<div class="container ">

    <div class="box">



<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-12">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name , :class=>"form-control ",:required=>true %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form.label :budget %>
    <%= form.text_field :budget, id: :project_budget, :class=>"form-control "%>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :name, {prompt: "Select Client"}, {class: "form-control",:required=>true} %>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12">
     <%= form.submit  :class=>"btn btn-success"%>
  </div>
</div>
  
<% end %>


</div>
</div>
</div>

app/views/projects/detailed_report.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12" align="center">
      <h3>Project Cost Detail</h3>
    </div>
  </div>
  <div class="col-md-10"></div>
  <div class="col-md-2" align="right">
    <%= link_to 'Back', :back, :class => "btn btn-danger" %>
  </div>

  <div class="col-md-12 box">
    <table class="table table-striped table-bordered">
      <thead class="table_head">
        <tr>
          <th>Employee Name</th>
          <th>Hours</th>
          <th>Cost</th>
        </tr>
      </thead>
      <tbody>
        <% hours, cost = [], [] %>
        <% @employee_details.each do |employee| %>
          <tr>
            <td><%= employee[:employee_name] %></td>
            <td style="text-align: right">
              <% hours << employee[:hours] %>
              <%= employee[:hours].round %>
            </td>
            <td style="text-align: right">
              <% cost << employee[:cost] %>
              <%= employee[:cost].round %>
            </td>
          </tr>
        <% end %>
        <tr>
          <th>Till Consumed</th>
          <th style="text-align: right">
            <%= hours.compact.sum.round %>
          </th>
          <th style="text-align: right">
            <%= cost.compact.sum.round %>
          </th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/edit.html.erb
<center><h3>Editing Project</h3></center>

<div style="float: right; margin: 5px 65px;">

<%= link_to 'Show', @project ,:class=>"btn btn-danger" %>
<%= link_to 'Back', project_path ,:class=>"btn btn-success" %>

</div>
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="container-fluid">
  <%#= link_to 'Reports', project_report_path ,:style=>"color:#fff;float:right;margin-right:10px;",:class=>"btn btn-primary" %>
  <%= link_to 'Add Project', new_project_path ,:style=>"color:#fff;float:right;margin-right:10px;",:class=>"btn btn-primary" %>
  <!-- <div class="row container-fluid " style="margin-top: 40px;"> -->
    <center><h3><b>Projects<b></h3></center>
    
    <div class="col-md-12 box">
      <table class="table table-striped table-bordered" id="table_id">
        <thead class="table_head">
          <tr>
            <th>Project </th>
            <th>Client</th>
            <th>Budget</th>
            <!-- <th>Status</th> -->
            <th>Action</th>
            
           <!--  <th><center>Delete</center></th> -->
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= project.client.name %></td>
              <td style="text-align:right;"><%= project.budget.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></td>
              <!-- <td style="text-align:center;">
                <label class="switch">
                  <input type="checkbox" <!% if project.status == true %> checked <!% end %> value='<!%=project.id%>' class='clickoperation'>
                  <span class="slider round"></span>
                </label>
              </td> -->
              <% if project.status == true %>
                <td><%= link_to 'View', project %>&nbsp;|&nbsp;<%= link_to 'Edit', edit_project_path(project) %>&nbsp;|&nbsp;<%= link_to "Active", projects_project_active_status_path(id: project, status: false), data: { confirm: 'Are you sure to turn Inactive?' } %></td>
              <% else %>
                <td><%= link_to 'View', project %>&nbsp;|&nbsp;<%= link_to 'Edit', edit_project_path(project) %>&nbsp;|&nbsp;<%= link_to "Inactive", projects_project_active_status_path(id: project, status: true), data: { confirm: 'Are you sure to turn Active?' } %></td>
              <% end %>
              <!-- <td><center><!%= link_to '', project, method: :delete, data: { confirm: 'Are you sure?' },:class=>"fa fa-trash-o" %></center></td> -->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <!-- </div> -->
</div>

<br>

<script type="text/javascript">
  $(".clickoperation").click(function () {
    var id=($(this).val());
    //var id=($(this).prop("checked")
    if ($(this).prop("checked")== true){
      $.ajax({
        url: "projects/project_active_status",
        data: {id: id,status: true},
        dataType: 'script'
     })    
    }
    else {
      $.ajax({
         url: "projects/project_active_status",
         data: {id: id,status: false},
         dataType: 'script'
      })
    }    
  });
</script>

<style>
.switch {
  position: relative;
  display: inline-block;
  width: 60px;
  height: 34px;
}

.switch input {display:none;}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>

app/views/projects/new.html.erb
<center><h3>New Project</h3></center>

<div style="float: right; margin: 5px 65px;">

<%= link_to 'Back', projects_path ,:class=>"btn btn-danger"%>

</div>

<%= render 'form', project: @project %>

app/views/projects/project_report.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css"/>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script> -->

<div class="container-fluid">
  <div class="col-md-12 row">      
    <div class="col-md-8">
      <div class="col-md-4">
        <label>Project Name</label>
      </div>
      <div class="col-md-3">
        <label>From Date</label>
      </div>
      <div class="col-md-3">
        <label>To Date</label>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
  <%= form_for(Project.new, url: project_report_path) do |f| %>
    <div class="col-md-12 row">
      <div class="col-md-8">
        <div class="col-md-4">
          <% if @project_reports.count == 1 %>
            <% @project_reports.each do |project| %>
              <%= f.select :id, options_from_collection_for_select(@projects, "id", "name", Project.where(name:project[0]).ids[0]), {prompt: "All"}, class: "form-control" %>
            <% end %>
          <% else %>
            <%= f.collection_select :id, @projects, :id, :name, {prompt: "All"}, {class: "form-control"} %>
          <% end %>
        </div>
        <div class="col-md-3">
          <input type="text" name="from_date" class="form-control" id="dt1" required="true" readonly="true" value="<%= @from_date.to_date.strftime('%d-%m-%Y') %>" >
        </div>
        <div class="col-md-3">
          <input type="text" name="to_date" class="form-control" id="dt2" required="true" readonly="true" value="<%= @to_date.to_date.strftime('%d-%m-%Y') %>">
        </div>
        <div class="col-md-2">
          <%= f.submit 'Get Report', class: "btn btn-primary", id: "report", "data-disable-with": false %>
        </div>
      </div>
    </div>
  <% end %>

  <br>

  <% if @project_reports.present? %>
  	<div class="row container-fluid " style="margin-top: 40px;">
  	  <center><h3>Project Cost Report from <%= @from_date.to_date.strftime("%a, %d-%m-%Y") %> to <%= @to_date.to_date.strftime("%a, %d-%m-%Y") %></h3></center>
      
      <%unless params["data"].present?%>
        <div style="float: right; margin: 5px 65px;">
          <%= link_to 'Back', :back,:class=>"btn btn-danger" %>
        </div>
      <%end%>

  	  <div class="col-md-12 box">
      	<table class="table table-striped table-bordered" id="table_id">
          <thead class="table_head">
            <tr>
              <th>S.No</th>
              <th>Project</th>
              <th>Hour (This Period)</th>
              <th>Cost (This Period)</th>
              <th>Till Consumed Hours</th>
              <th>Till Consumed Cost</th>
            </tr>
          </thead>
          <tbody>
          	<% s=1 %>
          	<% @project_reports.each do |project| %>
        	  <tr>
          	  	<td align="right"><%= s %></td>          	  	
          	  	<td><%= project[0] %></td>
          	  	<td style="text-align:right;"><%= project[1] %></td>
          	  	<td style="text-align:right;"><%= project[2] %></td>
          	  	<td style="text-align:right;"><%= project[3] %></td>
          	  	<td style="text-align:right;">
                  <% if project[4] == 0 %>
                    <%= project[4] %> 
                  <% else %> 
                    <%= link_to "#{project[4]}", detailed_report_path(name: project[0]) %>
                  <% end %>
                </td>
              </tr>
        	  <% s+=1 %>
          	<% end %>
          </tbody>
      	</table>
      </div>
  	</div>

  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $("#dt1").datepicker({
      dateFormat: "dd-mm-yy",
      maxDate:'+0d',
      onSelect: function (date) {
        var dt2 = $('#dt2');
        var startDate = $(this).datepicker('getDate');
        var minDate = $(this).datepicker('getDate');
        dt2.datepicker('setDate', minDate);
        startDate.setDate(startDate.getDate() + 60);        
        dt2.datepicker('option', 'minDate', minDate);
        dt2.datepicker('option', 'maxDate', 0);
        //dt2.datepicker('option', 'maxDate', '0');
      }
    });
    $('#dt2').datepicker({
      dateFormat: "dd-mm-yy",
      maxDate:'+0d'
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function() { 
    $("#dt1").each(function(ev) {
      if(!$(this).val()) { 
        $(this).attr("placeholder", "dd-mm-yy");
      }
    });
    $("#dt2").each(function(ev) {
      if(!$(this).val()) { 
        $(this).attr("placeholder", "dd-mm-yy");
      }
    });
  });
</script>

app/views/projects/show.html.erb
<div class="row container ">
<center><h3>Project Details</h3></center>
<div style="float: left; margin-left: 190px;">

<%= link_to  'Edit', edit_project_path(@project) ,:class=>"btn btn-success" %>
<%= link_to 'Back', projects_path,:class=>"btn btn-danger" %>
</div>
<br>
<div class="col-md-11 col-md-offset-2 box">
<table class="table">
 <tbody>
    <tr>
      <td class="fontcolr">Project Name </td>
      <td><%= @project.name %></td>

      </tr>
    <tr>
      <td class="fontcolr">Budget</td>
      <td><%= @project.budget.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></td>
    </tr>
    <tr>
      <td class="fontcolr"> Client </td>
      <td><%= @project.client.name %></td>
    </tr>
    
    
</tbody>
</div>

</div>